In [ ]:
import numpy as np # Import NumPy

In [ ]:
nums = [1,2,3,4,5]

array1 = np.array(nums) # Create an array from list

print(array1) 

[1 2 3 4 5]


In [ ]:
zero_array = np.zeros(5) # Create an array of five 0s
print(zero_array)


[0. 0. 0. 0. 0.]


In [ ]:
one_array = np.ones(3) # Create an array of three 1s
print(one_array)

[1. 1. 1.]


In [13]:
range_array = np.arange(1, 10, 2) # Create an array but with a for loop
print(range_array)

[1 3 5 7 9]


In [ ]:
random_array = np.random.randint(1, 100, 5) # Create a for loop array but randomly
print(random_array)

[ 5  9 41 23 29]


In [ ]:
random_matrix = np.random.rand(3,3) # Create a matrix of size three cross three with random values 
print(random_matrix)

[[0.00574596 0.12016556 0.31428598]
 [0.62456647 0.21219866 0.36325114]
 [0.8345963  0.91682173 0.78741614]]


In [ ]:
shape = range_array.shape # Shape of the matrix
print(shape)

(5,)


In [15]:
size = range_array.size # Size of the matrix
print(size)

5


In [ ]:
dtype = random_array.dtype # Type of the array
print(dtype)

int32


In [ ]:
print(range_array.ndim) # Demention of the array

1
