In [1]:
import numpy as np

In [2]:
array1 = np.array([10,20,30,40,50])

In [3]:
second_element = array1[1]
print(second_element)

20


In [4]:
print(array1[-2])

40


In [ ]:
sliced_arr = array1[1:4] # Index is one and slice until 3 (4-1 = 3)
print(sliced_arr)

[20 30 40]


In [6]:
step_arr = array1[::2]
print(step_arr)

[10 30 50]


In [ ]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [8]:
element = matrix[1,1]
print(element)

5


In [10]:
second_row = matrix[1,:]
print(second_row)

[4 5 6]


In [12]:
second_column = matrix[:,1]
print(second_column)

[2 5 8]


In [ ]:
data = np.array([1,2,3, np.nan, 4,5])
missing = np.isnan(data)            # Missing or no records
print(missing)

[False False False  True False False]


In [15]:
data_fill = np.nan_to_num(data, nan = 100)
print(data_fill)

[  1.   2.   3. 100.   4.   5.]
